Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 8
    Handler: main.handler
    Environment:
      Variables:
        DB_HOST: db-ecefall452.chkeokiu8zrk.us-east-2.rds.amazonaws.com
        DB_NAME: knight_db
        DB_PASSWORD: chickenNugget452!
        DB_USER: masterknight
    VpcConfig:
      SecurityGroupIds:
        - sg-0964fb63a9b5bc0e9
      SubnetIds:
        - subnet-042c1e86932d10a39
        - subnet-040296c7a5480bab1
        - subnet-04c8960b424ac23bb

Resources:
  knightAPIforum:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: knightAPI_forum
      CodeUri: ./functions/forum
      Role: arn:aws:iam::147997151910:role/service-role/knightAPI_forum-role-jmtrdpyb
      Layers: 
        - arn:aws:lambda:us-east-2:147997151910:layer:mysql2-layer:1
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/knightAPI_forum
      MemorySize: 128
      Architectures: 
        - x86_64
      Events:
        ForumGet:
          Type: Api
          Properties:
            Path: /forum
            Method: GET
        ForumPost:
          Type: Api
          Properties:
            Path: /forum
            Method: POST
        ForumPut:
          Type: Api
          Properties:
            Path: /forum
            Method: PUT
        ForumDelete:
          Type: Api
          Properties:
            Path: /forum
            Method: DELETE
  
  knightAPImarketplace:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: knightAPI_marketplace
      CodeUri: ./functions/marketplace
      Role: arn:aws:iam::147997151910:role/service-role/knightAPI_marketplace-role-xuhmupfg
      Layers: 
        - arn:aws:lambda:us-east-2:147997151910:layer:mysql2-layer:1
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/knightAPI_marketplace
      MemorySize: 128
      Architectures: 
        - x86_64
      Events:
        MarketplaceGet:
          Type: Api
          Properties:
            Path: /marketplace
            Method: GET
        MarketplacePost:
          Type: Api
          Properties:
            Path: /marketplace
            Method: POST
        MarketplacePut:
          Type: Api
          Properties:
            Path: /marketplace
            Method: PUT
        MarketplaceDelete:
          Type: Api
          Properties:
            Path: /marketplace
            Method: DELETE